### ISSUE TITLE
Časový posun +2

### ISSUE THREAD

**Issue by koperfieldcz** [Sorien/plugin.video.sl#10]
http://www.xbmc-kodi.cz/prispevek-skylink-livetv-addon-beta?page=2

Asi je třeba přidat +0200 k start a stop v exports.py.

**Comment by Sorien** [comment]
cas EPG je v UTC (overene) + specifikacia hovori ze ak tam neni "+xxxx" tak sa cas povazuje za UTC tento format pozna IPTVSimple (overene) 

z https://github.com/Sorien/plugin.video.sl/blob/master/exports.py#L49 treba odstranit `datetime.timedelta(hours=1)` (kompenzacia bugu pre windows")

| OS | EPG | Playback |
| --- | --- | --- |
| win | ok (treba nastavit timeshift -1) | ok |
| android | ok | -2hod |
| linux | | |

**Comment by Sorien** [comment]
https://trac.kodi.tv/ticket/17943

**Comment by koperfieldcz** [comment]
Snad solved. #11
