### ISSUE TITLE
Přidání do CZ/SK repozitáře

### ISSUE THREAD

**Issue by koperfieldcz** [Sorien/plugin.video.sl#13]
Přestože Kodi 18 ještě není vydáno, navrhuji přidání pluginu do CZ/SK repozitáře po vydání release 1.0. Jde hlavně o aktualizace pluginu, disclaimer stejně upozorňuje uživatele na funkčnost. Zajímá mne názor @Sorien, zbytek jsem schopen udělat sám.

**Comment by Sorien** [comment]
@koperfieldcz som za 👍

**Comment by koperfieldcz** [comment]
Ok, zařídím to.
