### ISSUE TITLE
Kanály i EPG nefunkční

### ISSUE THREAD

**Issue by koperfieldcz** [Sorien/plugin.video.sl#14]
http://www.xbmc-kodi.cz/prispevek-skylink-livetv-addon-beta?pid=47791#pid47791

Skylink (resp. Solocoo, společnost, která OTT Skylinku provozuje) zřejmě změnil API. Je třeba se na to podívat, nejedná se o ojedinělý případ.

Požádal jsem na fóru o logy, budu o nich informovat.

**Comment by Sorien** [comment]
u mna to spravilo to iste je tam taky rychly fix a nova verzia hadam to pomoze

**Comment by koperfieldcz** [comment]
Zřejmě je vyřešeno.
