### ISSUE TITLE
Nefunguje na OSMC

### ISSUE THREAD

**Issue by koxkox** [Sorien/plugin.video.sl#21]
Pre inštáláciu na OSMC 2018-12 je potrebné doinštalovať balíček **xbmc.python-2.26.0**, inak padne inštalácia. Po úspešnej inštalácii v nastaveniach je potrebné zmeniť providera, aby sa zapísal do nastavení, inak bude v settings.xml:
`<setting id="provider" value="" />`
a potom plugin padá. Po uložení nastavení sa stiahne EPG aj Playlist, no prehrať nejde, padá z chybou:

```
14:11:51.382 T:1926072832  NOTICE: VideoPlayer: Opening: pvr://channels/tv/All channels/pvr.iptvsimple_1503496288.pvr
14:11:51.382 T:1926072832 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:11:51.383 T:1453134592  NOTICE: Creating InputStream
14:11:51.411 T:1453134592 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sl/?action=play&id=rzxqQ-kzUkG3x2PGEaxnFAAAAAE
14:11:51.412 T:1453134592   ERROR: CDVDInputStreamPVRManager::Open - error opening [plugin://plugin.video.sl/?action=play&id=rzxqQ-kzUkG3x2PGEaxnFAAAAAE]
14:11:51.412 T:1453134592   ERROR: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/All channels/pvr.iptvsimple_1503496288.pvr]
14:11:51.412 T:1453134592  NOTICE: CVideoPlayer::OnExit()
14:11:51.441 T:1926072832  NOTICE: CVideoPlayer::CloseFile()
14:11:51.441 T:1926072832  NOTICE: VideoPlayer: waiting for threads to exit
14:11:51.441 T:1926072832  NOTICE: VideoPlayer: finished waiting
14:11:51.442 T:1926072832  NOTICE: CVideoPlayer::CloseFile()
14:11:51.442 T:1926072832  NOTICE: VideoPlayer: waiting for threads to exit
14:11:51.442 T:1926072832  NOTICE: VideoPlayer: finished waiting
```
Zrejme ide o neaktuálny plugin **inputstream.adaptive**, ktorý je aktuálne vo verzii 2.3.13, no OSMC beží na verzii Debian 9, pre ktorý ma posledný [build 2.0.19](https://kodi-addons.club/addon/inputstream.adaptive/2.3.13) (v Kodi 2.0.20).

**Comment by Sorien** [comment]
na aku veriu kodi sa to pokusas nainstalovat? addon je kompatibilny iba s kodi v18

podla https://kodi.wiki/view/Addon.xml ma Kodi v18 min versiu python addonu 2.26.0 aka konkretne je verzia v osmc? ... mozem to upravit v podstate je jedno aku pouzivame jediny ucel bol zabranit nainstalovaniu pluginu na kodi < v18

nemas nahodou log pred tou zmenou providera toto by nemalo sposobit chybu

unsupported protocol(plugin) z logu ukazuje ze Kodi je starsi ako v18beta2, kedy bola pridana podpora pre plugin protocol, ktory je potrebny pre nastavenie paramatrov streamu aby input stream adaptive addon vedel ako ma dekodovat stream.

**Comment by koxkox** [comment]
Mám aktuálnu verziu OSMC 2018.12-1, v ktorom beží Kodi 17.6, čo som si neuvedomil. Po upgrade na verziu 18.1 RC2 [podľa návodu](https://discourse.osmc.tv/t/testing-kodi-18-leia-builds-for-raspberry-pi/20631) beží bez problémov. V ďalšej verzii OSMC 2019.X už asi bude všetko v poriadku.
