### ISSUE TITLE
KeyError: 'name' 

### ISSUE THREAD

**Issue by lukasmrtvy** [Sorien/plugin.video.sl#22]
Na platforme flatpak(x64) https://flathub.org/apps/details/tv.kodi.Kodi dostavam chybu:
Verze addonu 1.0.0
Nejake napady?

```
WARNING: CPythonInvoker(1, /home/kodi/.var/app/tv.kodi.Kodi/data/addons/plugin.video.sl/service.py): the python script "/home/kodi/.var/app/tv.kodi.Kodi/data/addons/plugin.video.sl/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'name'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.var/app/tv.kodi.Kodi/data/addons/plugin.video.sl/service.py", line 36, in onSettingsChanged
                                                res = self.update(True)
                                              File "/home/kodi/.var/app/tv.kodi.Kodi/data/addons/plugin.video.sl/service.py", line 55, in update
                                                d = self.select_device(e.devices)
                                              File "/home/kodi/.var/app/tv.kodi.Kodi/data/addons/plugin.video.sl/service.py", line 30, in select_device
                                                items.append(device['name'].replace("+", " "))
                                            KeyError: 'name'
                                            -->End of Python script error report<--
```

EDIT: tahle verze mi funguje https://www.xbmc-kodi.cz/prispevek-skylink-livetv-addon?pid=62958#pid62958 

Respektive ta chyba vyse nastane tak ci tak, kdyz v nenastavenem IPTV Simple nastavim, ze chci aktualizovat seznam kanalu (jsou prazdne). Netusim, proc je do toho zapleteny plugin.video.sl, ale minimalne tohle v logu je. Je mozne, ze je to pise tak ci tak pro tento addon, kdyz neni nakonfigurovany, nebo nema dostupnou konfiguraci.

Nejak nechapu, kde je kod a proc to neni releasnuty? :)

Diky

**Comment by Sorien** [comment]
nemal som cas sa k tomu vratit, tv moc nesledujem, tento plugin vznikol skor nahodou :) ... 

pokial si pamatam v tej verzii som na rychlo pridal niake logovanie aby som nasiel inu chybu, releasnem to zajtra a skusim sa pozriet aj na ten tracelog

**Comment by lukasmrtvy** [comment]
Jinak tady jsem popisoval chybu https://www.xbmc-kodi.cz/prispevek-skylink-livetv-addon?pid=62912#pid62912, v 1.0.0 nefunguje, v 1.0.1 funguje

**Comment by Sorien** [comment]
ta chyba je zase nieco ine. 1.0.1 ma novu feature ak nie je dostupne ziadne zariadenie tak sa pouzije automaticky to najstarsie (v nastaveniach sa to da vypnut) preto sa uz tato chyba neobjavuje ale ak sa toto nastavenie vypne zase sa zacne objavovat ... je to niaky rozdiel v spravani sa python interpretera medzi platformami ak sa kombinuju viacere typy stringov, zjavne v python2 je v tom dost velky chaos

**Comment by Sorien** [comment]
tu chybu z prveho prispecku sa mi nepodarilo nasimulovat u mna device['name'] je vzdy naplnene

**Comment by lukasmrtvy** [comment]
Popravde se mi to nezobrazuje v 1.0.1, problem byl zpusobeny nekde v 1.0.0, netusim proc. 
Az budu mit chvilku, tak to vyzkousim na starsi verzi, jestli se stale projevuje.

**Comment by Sorien** [comment]
problem sa uz zjavne nevyskytuje tak zaviet tuto issue
