### ISSUE TITLE
Addon pravdepodobne zpusobuje nekorektni ukonceni Kodi.

### ISSUE THREAD

**Issue by lukasmrtvy** [Sorien/plugin.video.sl#23]
Mam takovej pocit, ze tenhle addon brani Kodi korektnimu ukonceni a nekdy Kodi musi dostat SIGKILL (v mem pripade po vyprseni systemd timeoutu), pouzivam systemd --user servicu.

Tady je kousek logu. Je mozny ze kvuli konstatnimu zapisu playlistu a epg se Kodi korektne neukonci?
```
2019-03-28 21:19:17.231 T:140022082684672 WARNING: CPythonInvoker(1, /home/kodi/.var/app/tv.kodi.Kodi/data/addons/plugin.video.sl/service.py): the python script "/home/kodi/.var/app/tv.kodi.Kodi/data/addons/plugin.video.sl/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2019-03-28 21:19:22.239 T:140023005149824   ERROR: CPythonInvoker(2, /home/kodi/.var/app/tv.kodi.Kodi/data/addons/script.common.plugin.cache/default.py): script didn't stop in 5 seconds - let's kill it
```

**Comment by Sorien** [comment]
v tom logu su dve veci #1 ostava tam referencovana trieda xbmcaddon.Addon a garbage collector ju nevie uvolnit toto by malo byt opravitelne, ta #2 je ze niaky plugin sa neukonci v stanovenom case ci je to tento to netusim, aj ked by mohol. Plugin spusta na pozadi sluzbu https://github.com/Sorien/plugin.video.sl/blob/master/service.py ktora zabezpecuje ze raz za 12 hodin sa reloadne playlist a epg, z niakeho dovodu sa mozno tato sluzba dost skoro neukonci, aj ked https://github.com/Sorien/plugin.video.sl/blob/master/service.py#L123 by malo zabezpecit aby sa ukoncila spolu s kodi bez delayu. Pozriem vecer.

**Comment by Sorien** [comment]
`#1` Fixnuty commitom https://github.com/Sorien/plugin.video.sl/commit/27000791e3b43db8f1ef96afb3881f9707080de6

`#2` U mna sa nic taketo v logoch nie je, pravdepodobne sa jedna o python plugin script.common.plugin.cache na ktorom tento addon nie je  zavysly ale napr streamcinema je treba skusit na cistej instalacii

**Comment by lukasmrtvy** [comment]
Diky, co se tyce `#2`, tak jsem nasel zavislost:
```
addons/script.module.stream.resolver/addon.xml:    <import addon="script.common.plugin.cache" version="2.5.5"/
addons/plugin.video.ivysilani/addon.xml:        <import addon="script.module.stream.resolver" version="1.6.13"/>
```
