### ISSUE TITLE
nefunguje

### ISSUE THREAD

**Issue by cyberreality** [Sorien/plugin.video.sl#35]
tak dneska kolem poledne to prestalo jet, ony se i dost zmenily stranky : https://livetv.skylink.cz

**Comment by Sorien** [comment]
ich webovy klient ti ide? lebo ja nemam dostupny zidny tv program cez web

**Comment by cyberreality** [comment]
jo, na webu v pohode, v tv pruvodci normaln eprehled programu a muzu se i divat na cokoliv zive/zaznam.
zkusil sem i na tabletu v jejich androidi aplikaci a taky vse funguje ...

**Comment by Sorien** [comment]
zatial to nevyzera az tak zle, niake veci bude treba prerobit ak ma cache nepredbehne zajtra by mohla byt vonku oprava

**Comment by Sorien** [comment]
je uvolnena nova verzia 1.4.1 s opravou
