### ISSUE TITLE
Je mozne ze pro plugin odpoji nespravne zariadenie ak su vsetky 4 obsadene

### ISSUE THREAD

**Issue by Sorien** [Sorien/plugin.video.sl#38]
```
{'error': 'toomany', 'id': 'xxx',
                    'secret': '1::', 'action': 0, 'devices': [
            {'id': 'z1', 'name': 'Chrome', 'type': 'web',
             'lastactivity': -62135596800000},
            {'id': 'z2', 'name': 'Chrome', 'type': 'web',
             'lastactivity': -62135596800000},
            {'id': 'z3', 'name': 'Chrome', 'type': 'web',
             'lastactivity': 1563396292564},
            {'id': 'z4', 'name': 'Chrome', 'type': 'web',
             'lastactivity': -62135596800000}]}
```
tie casi `lastactivity` su niake divne

**Comment by Sorien** [comment]
pravdepodobne tie s -xxx sa aktualne pouzivaju

**Comment by assky** [comment]
Mne tento negatívny timestamp ukazuje len pre device s týmto addonom. Pri webovom device mám timestamp vždy kladný a teda správny - navyše som si všimol, že sa aktualizuje vždy pri spustení streamu na webe.

**Comment by Sorien** [comment]
dik za info, takze nieco nerobime tak ako by sme mali, trochu som sa toho bal lebo plugin pouziva iba malu cast volani api oproti webovej apke

**Comment by Sorien** [comment]
je to fixnute https://github.com/Sorien/plugin.video.sl/pull/40
