### ISSUE TITLE
premenovat plugin

### ISSUE THREAD

**Issue by Sorien** [Sorien/plugin.video.sl#4]
z plugin.video.sl na nieco ako 

service.pvr.skylinklivetv
pvr.service.skylink.livetv

**Comment by dmnc-net** [comment]
nenazyval bych to pvr, kdyz to neni pvr client ...

**Comment by Sorien** [comment]
hmm toto uz nema cenu riesit, kodi nepodporuje ziadne migracie a ziadat od uzivatelov aby vsetko nastavovali odznovu len koli nazvu ...
