### ISSUE TITLE
Rychlejsie prepinanie programov

### ISSUE THREAD

**Issue by Sorien** [Sorien/plugin.video.sl#42]
pravdepodobne je mozne vynechat volanie `self._login` https://github.com/Sorien/plugin.video.sl/blob/master/skylink.py#L236

ulozenim `.ASPXAUTH` cookie predchadzajuceho spojenia

**Comment by cache-sk** [comment]
Ale musi tam byt aj nejake casove ohranicenie platnosti, aby sa nestalo ze preberie device slot ine zariadenie (ked niekto zdiela napr. 1 slot medzi viac kodi a web prehliadacmi)..

**Comment by Sorien** [comment]
jj podla toho co som nasiel defaultne by tam mal byt timeout na serveri 20-30min a zariadenie moze byt pocas tejto doby disconnecnute 

problem je ze requesty s uid uz neexistujuceho zariadenia trvaju v radoch sekund
