### ISSUE TITLE
nefunguje pvr 

### ISSUE THREAD

**Issue by realq0** [Sorien/plugin.video.sl#58]
ahoj, mam rp3 librelec, kodi 18.5 .  robil som podla tohto navodu: https://www.xbmc-kodi.cz/prispevek-skylink-livetv-addon
ked si kliknem na tv, napise mi Spusta sa spravca PVR: 0%   . a tam to aj vzdy skonci.
Vedel by si mi stym pomoct? 

-fixed  na verzii 18.6 Funguje

**Comment by realq0** [comment]
fixed

**Comment by Sorien** [comment]
Zvycajne staci restart
