### ISSUE TITLE
addon.xml - requires

### ISSUE THREAD

**Issue by dmnc-net** [Sorien/plugin.video.sl#59]
navrhuji do addon.xml pridat zavislost na `pvr.iptvsimple`

**Comment by Sorien** [comment]
mozno sa nieco zmenilo ale kodi vedel riesit iba zavislosti medzi python addonami, ked som tam pridal  binarny addon nerobilo to nic

**Comment by cache-sk** [comment]
ale plugin je pouzitelny aj bez pvr.iptvsimple priamo ako video doplnok, aj ked je primarne urceny na generovanie playlistu a epg..

**Comment by dmnc-net** [comment]
@Sorien to netuším, kdyby to však umělo, bylo by to každopádně snazší. Na druhou stranu to dává smysl, je to binární, dokonce na linuxu se pvr installuje většinou z repo systému.

@cache-sk to je pravda, na archiv a VoD jede i bez pvr, pak je otázkou, koho by to štvalo víc :)

_... pokud to nejde, asi nezbývá než ticket zavřít_
