### ISSUE TITLE
Works with UPC Direct Now (HU)

### ISSUE THREAD

**Issue by Pityke1105** [Sorien/plugin.video.sl#60]
Hello,

I just wanted to let you know that your code with minor modifications is working well with the hungarian UPC Direct also.

After I added the modifications I noticed that it was not the newest version and you modified the corresponding parts (M7 domain handling), but if you are interested in implementing the hungarian UPC direct to your code I can provide you the details and I’m willing to add the hungarian localization. I know nothing about python so I won’t be able to maintain a code like this but I believe your code should work not just with UPC direct but every M7 group related IPTV like Canal Digitaal, HD Austria, Focus SAT, etc.

So let me know if you are interested and thank you for your great work!

**Comment by Sorien** [comment]
this plugin will never be in the official repository, and there are no intentions to support more providers/countries just fixing bugs from time to time, you can make your changes public to your own fork as a starting point if somebody would like to continue with our work, but I don't expect to be merged to master thx
