### ISSUE TITLE
No stream on device with Android 5.1.1 

### ISSUE THREAD

**Issue by johnnz47** [Sorien/plugin.video.sl#62]
Hello, 
I have Minix Neo X8-H Plus box running on Android 5.1.1 which is the last supported version for this box. I am using latest Kodi version 18.8.0 version and your latest version of Skylink Live TV 1.6.7. I have working and prepaid Skylink Live TV account.  I followed all 5 steps from https://www.xbmc-kodi.cz/prispevek-skylink-livetv-addon
but after I try to start the stream of any TV channel it is loading for 1 second and then nothing happens. When I tried the same for my Kodi running on my phone with Android 10 everything works like a charm with no issue. BTW1. SC2, Markíza, TA3 addons are working on my Minix box as well with no issue. Could you please check why streams are not working on Android 5.1.1 only for Skylink Live TV addon? 

BTW2.
I am also using latest
InputStream Helper v0.5.1
InputStream Adaptive v2.5.4

Thanks a lot for resolving my issue.

**Comment by Sorien** [comment]
install https://play.google.com/store/apps/details?id=com.androidfung.drminfo&hl=en_CA and check if your device is widevine certified (you should see there widevine cdm, s/t like https://lh3.googleusercontent.com/VSMVvE4QStkWv9N6qOKd5urrCDp6tOgMeKRz6LS6TTe0jXTgTMFuHFXVi4fX1ZcWzbk=w1920-h937-rw)

**Comment by johnnz47** [comment]
>
> Hi, thanks a lot for super quick answer :-)

I installed the app but it looks my Minix device is not Widevine CDM
compatible. When I launched the DRM test there is nothing about Widevine as
on your screenshot so it seems my device is not supported for DRM content
:-(
I have to buy new Android box device.


https://photos.app.goo.gl/rLq7k2xQBXVTMJ6M7

But thanks a lot for your great work with addon and your support :-)

Your fan
Jan

**Comment by Sorien** [comment]
you are right, it's not compatible, try to look at the internet maybe you could find some newer firmware with widevine certification

**Comment by cache-sk** [comment]
@johnnz47 You can also try to find working version of LibreELEC/CoreELEC or another fork.. if you have enough time and patience and will to reuse old box :) But, noone can guarantee it will work.

For example (first relevant google link) - https://forum.libreelec.tv/thread/12155-libreelec-9-0-kodi-18-x-for-minix-x8-x8h-x8h/

Note - LibreELEC and others are minimalistic linux with Kodi for boards like Raspberry PI and many china made android boxes (mostly Amlogic cpu based and yours seems to have Amlogic S802-H).

Learn more at https://libreelec.tv/ and https://coreelec.org/ and google. 

On *Elec system is widevine dowloaded as linux arm-v7 binary library from Google Chrome backup image during first attempt for playback.

**Comment by johnnz47** [comment]
Hello Peter,

Thanks a lot for your feedback and help. I will definitely try it 😉

Thank you
Best regards,
Jan


Dňa po 5. 10. 2020, 18:26 Peter Kaššák <notifications@github.com>
napísal(a):
