### ISSUE TITLE
Skylink na KODI

### ISSUE THREAD

**Issue by hochmi80** [Sorien/plugin.video.sl#67]
Dobrý den. Při instalaci Skylink na KODI (PC s Win10) jsem postupoval přesně podle návodu na XBMC-KODI, ale neuspěl jsem. Doplněk Skylink Live TV není ve službách, ale v doplňcích videa, nastavení jsem provedl přesně podle návodu, ale soubor playlist.m3u je stále prázdný. Můžete poradit? Děkuji.

**Comment by cache-sk** [comment]
Ten navod v prvom prispevku je uz trocha zastaraly, aj ked stale vela veci sedi. Stacilo si prejst cele vlakno, dokonca aj odkaz na video navod tam niekde tusim bol, pripadne pockat na odpoved, nie kazdy den sa venujem/e foru.
Kedze toto nieje Issue, zatvaram..

**Comment by hochmi80** [comment]
Dobrý den.

OK a děkuji. Zřejmě jsem se špatně díval na stránkování 😉. Omlouvám se...

Hezký večer.

Pavel

Dne út 1. pro 2020 21:16 uživatel Peter Kaššák <notifications@github.com>
napsal:
